### ISSUE TITLE
Catch bank endpoint errors

### ISSUE THREAD

**Issue by Stretch96** [tellerhq/beta-issues#14]
When making requests to teller.io and the bank is down for maintenance (eg. Natwest from 2am), Teller will respond with a 5xx status.

I'm not sure whether Teller just forwards status codes, but it would be good to be able to distinguish between Teller 5xx and Bank 5xx.

Best possible solution would be to have a consistent way to determine bank errors (eg. having the error returned, but as a 2xx), then any 5xx would be a Teller error

**Comment by stevegraham** [comment]
This is a bug. Teller should catch these errors and return the last available data. Thanks for the report.

**Comment by stevegraham** [comment]
Fixed and deployed. We now catch any intermittent errors and return last available data
