### ISSUE TITLE
Duplicate transactions from Natwest

### ISSUE THREAD

**Issue by Stretch96** [tellerhq/beta-issues#15]
When getting all transactions (`/accounts/:uuid/transactions`) from Natwest, the returned transactions have duplicates prior to the date '2013-10-14' or the 2940th transaction.

Currently it appears to be consistently after the 2940th transaction, but I'll confirm once I have more transactions to work with.

The duplicate transactions however have different `id`s

**Comment by stevegraham** [comment]
Are the duplicates earlier to the date  '2013-10-14', e.g. '2013-10-13' or after, e.g. '2013-10-15'?

**Comment by Stretch96** [comment]
The duplicates are earlier - eg. '2013-10-13'
