### ISSUE TITLE
Nationwide linked accounts

### ISSUE THREAD

**Issue by billbo99** [tellerhq/beta-issues#16]
Having setup Nationwide on teller.io I only see my FlexAccount listed under accounts.   I am unable to see my credit card transactions which are linked to the same enrollment.

**Comment by stevegraham** [comment]
Products without an account number and sort code are ignored by Teller at the moment. This includes credit cards. They'll be added when there is more coverage so we know how non-account products are represented by each bank.

**Comment by billbo99** [comment]
OK,  I guess there would also be linked mortgage accounts to think about too.
