### ISSUE TITLE
API transaction history

### ISSUE THREAD

**Issue by billbo99** [tellerhq/beta-issues#17]
How far back does teller.io hold transaction history ?

Is there an option to tell the API to get all transactions between two dates ?

I ask as I am only seeing transactions for my Nationwide account going back to June 7th,  whereas the online portal will let you search back 15 months.

**Comment by stevegraham** [comment]
The Nationwide adapter doesn't make the request for historical transactions. I'll revisit this and implement the APIs to grab historical transactions when I'm adding direct debits, etc to Nationwide, which will be after the Santander work is complete.
