### ISSUE TITLE
Any plans on adding rate limitations to the API ?

### ISSUE THREAD

**Issue by billbo99** [tellerhq/beta-issues#18]
Just wondering if you have any future plans to enable rate limitation on the API endpoints ?  
And if so what might they be ?

**Comment by stevegraham** [comment]
Most likely, yes. The rationale will be to protect the end-user, i.e. an overzealous API consumer sending too many requests such that it triggers a circuit breaker at the bank and locks the user out of the account. Do you have any thoughts on this, including what the limits should be?
