### ISSUE TITLE
Handle Santander passcode request

### ISSUE THREAD

**Issue by stevegraham** [tellerhq/beta-issues#5]
For some customers Santander requests mobile banking ID and security number only. For others it asks for another credential. 

- [x] Identify the API differences
- [x] Handle this in the client implementation

**Comment by stevegraham** [comment]
CC @waltfy

**Comment by billbo99** [comment]
any progress on this one ?   When I try to enter my 5 digit security code I get "is invalid"

* I have ordered a new set of ID's from the bank to reset things there

**Comment by stevegraham** [comment]
@billbo99 working on this today.

**Comment by stevegraham** [comment]
I've identified three different registration flows.
- pin substring, e.g 1st, 4th, 5th digits from mobile banking PIN
- full passcode and full PIN
- full PIN

Now working on implementing the two currently unimplemented ones (2 & 3)

**Comment by waltfy** [comment]
Great to hear, @stevegraham - thanks!

**Comment by stevegraham** [comment]
@waltfy @billbo99 can you confirm your Santander app logon screen is one of the following

![img_8661](https://user-images.githubusercontent.com/18622/28221938-3e7e41ac-68bd-11e7-8f52-45beae34f532.PNG)
![img_8660](https://user-images.githubusercontent.com/18622/28221940-3e8b960e-68bd-11e7-8ea7-c2d91c9ef46c.PNG)
![img_8659](https://user-images.githubusercontent.com/18622/28221939-3e853390-68bd-11e7-9445-730a6dcdc703.PNG)

**Comment by billbo99** [comment]
I see the 2nd one 
https://user-images.githubusercontent.com/18622/28221940-3e8b960e-68bd-11e7-8ea7-c2d91c9ef46c.PNG

**Comment by waltfy** [comment]
@stevegraham I also see the second screen.

**Comment by stevegraham** [comment]
OK these flows are now handled in the back-end. Just need to add a view to the front-end service now.

**Comment by stevegraham** [comment]
Front-end work is done. Deploying this tomorrow.

**Comment by stevegraham** [comment]
This is in prod. Can you give it a go?

**Comment by stevegraham** [comment]
Let me know if you have any problems. I've worked out the flow via reverse engineering but don't have real accounts that use those two flows.

**Comment by waltfy** [comment]
@stevegraham awesome man thanks, something's up though - getting `500s` when clicking 'Next ' at the 'Connect your bank' page at the moment.

**Comment by stevegraham** [comment]
Might be a temporary issue. I've just clicked through the customer number page for a new Santander enrolment and didn't get a 500. Thanks for letting me know, I'll look in the logs.

**Comment by billbo99** [comment]
500 code here too

Internal Server Error
Something went wrong while serving this page.Please try again in a minute and email support at help@teller.io if you get this page again.

**Comment by stevegraham** [comment]
What page is this on, i.e. Steps to replicate.

**Comment by stevegraham** [comment]
Does this happen after entering customer number? If so I know what's happened.

**Comment by stevegraham** [comment]
I don't think the front-end service was redeployed. I've just done so now. If the error was happening after entering customer number it was most likely this. If so you should be able to resume the enrolment now.

**Comment by billbo99** [comment]
Enrolment completed now,  and I can see my accounts.  However none of them have a link to see transactions,  and when I try manually I get a 502 error via the API
{"error":{"message":"Gateway error","code":502}}

**Comment by stevegraham** [comment]
Transactions for Santander isn’t done yet. Working on that now (along with the other subresources)

S

**Comment by stevegraham** [comment]
Fixed.

**Comment by waltfy** [comment]
@stevegraham it's working, so ace - thank you! 🙏

**Comment by stevegraham** [comment]
@waltfy Awesome. Now to deliver all of the subresources. :)

**Comment by stevegraham** [comment]
I have Santander transactions running locally. Will hopefully have this deployed some time tomorrow.

```json
[
  {
    "type": "card_payment",
    "running_balance": "8.01",
    "links": {
      "self": "http://localhost:5050/accounts/503f99ef-65c8-4a6b-bc4d-9c0c3cd27612/transactions/b981e1bc-0118-40a4-b876-f0ef3adbc042"
    },
    "id": "b981e1bc-0118-40a4-b876-f0ef3adbc042",
    "description": "3.37 GBP, RATE 1.00/GBP ON 24-04-2017",
    "date": "2017-04-26",
    "counterparty": "MCDONALDS",
    "amount": "-3.37"
  },
  {
    "type": "card_payment",
    "running_balance": "11.38",
    "links": {
      "self": "http://localhost:5050/accounts/503f99ef-65c8-4a6b-bc4d-9c0c3cd27612/transactions/4911d8ef-6fd0-4d3f-ac70-f42470cce187"
    },
    "id": "4911d8ef-6fd0-4d3f-ac70-f42470cce187",
    "description": "2.75 GBP, RATE 1.00/GBP ON 24-04-2017",
    "date": "2017-04-26",
    "counterparty": "SAINSBURYS S/MKTS",
    "amount": "-2.75"
  },
  {
    "type": "card_payment",
    "running_balance": "14.13",
    "links": {
      "self": "http://localhost:5050/accounts/503f99ef-65c8-4a6b-bc4d-9c0c3cd27612/transactions/b492d4c6-a2d1-4978-9a86-b8d5444b8379"
    },
    "id": "b492d4c6-a2d1-4978-9a86-b8d5444b8379",
    "description": "2.50 GBP, RATE 1.00/GBP ON 24-04-2017",
    "date": "2017-04-26",
    "counterparty": "STARBUCKS",
    "amount": "-2.50"
  },
  {
    "type": "card_payment",
    "running_balance": "16.63",
    "links": {
      "self": "http://localhost:5050/accounts/503f99ef-65c8-4a6b-bc4d-9c0c3cd27612/transactions/2096673d-ecc5-4a9c-ad70-65056a21c2a0"
    },
    "id": "2096673d-ecc5-4a9c-ad70-65056a21c2a0",
    "description": "3.37 GBP, RATE 1.00/GBP ON 23-04-2017",
    "date": "2017-04-25",
    "counterparty": "MCDONALDS",
    "amount": "-3.37"
  },
  {
    "type": "transfer",
    "running_balance": "20.00",
    "links": {
      "self": "http://localhost:5050/accounts/503f99ef-65c8-4a6b-bc4d-9c0c3cd27612/transactions/854b22fe-5b23-4f7c-9e03-e328a0e7a6c2"
    },
    "id": "854b22fe-5b23-4f7c-9e03-e328a0e7a6c2",
    "description": "TRANSFER FROM MR STEVEN JAMES THOMAS GRAHAM",
    "date": "2017-04-24",
    "counterparty": "MR STEVEN JAMES THOMAS GRAHAM",
    "amount": "20.00"
  }
]
```

**Comment by waltfy** [comment]
@stevegraham this is wild, man. Such great work!
